services:
  grok2api:
    build: .
    container_name: grok2api
    environment:
      - API_KEY=sk-gweidwei008
      - IS_TEMP_CONVERSATION=true
      - SHOW_SEARCH_RESULTS=true
      - SHOW_THINKING=true
      - DISABLE_DYNAMIC_HEADERS=true
      - MANAGER_SWITCH=true
      - ADMINPASSWORD=sk-gweidwei008
    volumes:
      - ./data:/data
    ports:
      - 8002:5200